AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS Service with Service Connect and Task Tags"

Parameters:
  ClusterName:
    Type: String
    Description: "ECS Cluster Name"
  
  ServiceName:
    Type: String
    Description: "ECS Service Name"

  ContainerImage:
    Type: String
    Description: "Container image for the ECS task"

  ServiceTag:
    Type: String
    Description: "Tag version for Service Connect and Task"

Resources:
  # VPC
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: "MyVPC"

  # ECS Cluster
  MyCluster:
    Type: AWS::ECS::Cluster
    Properties: 
      ClusterName: !Ref ClusterName

  # ECS Task Definition
  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ServiceName}-task-family"
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: arn:aws:iam::your-account-id:role/ecsTaskExecutionRole
      ContainerDefinitions:
        - Name: !Sub "${ServiceName}-container"
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub "/ecs/${ServiceName}"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: "ecs"
      Tags:
        - Key: "version"
          Value: !Ref ServiceTag
        - Key: "Name"
          Value: !Sub "${ServiceName}-task"

  # ECS Service
  MyService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyCluster
      TaskDefinition: !Ref MyTaskDefinition
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - subnet-12345678  # Replace with your subnet IDs
            - subnet-87654321
          SecurityGroups:
            - sg-12345678  # Replace with your security group
          AssignPublicIp: ENABLED
      ServiceRegistries:
        - RegistryArn: arn:aws:servicediscovery:your-region:your-account-id:service/srv-xxxxxx  # Service Connect設定に対応するARN
      Tags:
        - Key: "version"
          Value: !Ref ServiceTag
        - Key: "Name"
          Value: !Ref ServiceName

  # Service Connect Configuration
  MyServiceConnect:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyCluster
      TaskDefinition: !Ref MyTaskDefinition
      DesiredCount: 2
      ServiceRegistries:
        - RegistryArn: arn:aws:servicediscovery:your-region:your-account-id:service/srv-xxxxxx  # 例のARN
      Tags:
        - Key: "version"
          Value: !Ref ServiceTag
